"""
DockerDeployer — optional Docker-based deployment for MCP servers.

Generates a Dockerfile, builds an image, and runs the container. Gracefully
degrades if Docker is not installed (docker_available = False).
"""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

DOCKERFILE_TEMPLATE = """\
# Auto-generated by MCP PAAS
FROM python:3.12-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE {port}
CMD ["uvicorn", "{entry_point}", "--host", "0.0.0.0", "--port", "{port}"]
"""


class DockerDeployer:
    """Docker deployment support with graceful degradation."""

    def __init__(self) -> None:
        self._docker_available = self._check_docker()

    # ----------------------------------------------------------------
    # Public API
    # ----------------------------------------------------------------

    def check_docker(self) -> bool:
        """Return whether Docker is available on this system."""
        return self._docker_available

    def generate_dockerfile(self, server_id: str, registry, output_dir: str | Path | None = None) -> None:
        """Generate a Dockerfile for a registered server."""
        server = registry.get_server(server_id)
        if server is None:
            raise KeyError(f"Server '{server_id}' not found in registry")

        target_dir = Path(output_dir or server.source_path)
        dockerfile = DOCKERFILE_TEMPLATE.format(
            port=server.port,
            entry_point=server.entry_point,
        )
        (target_dir / "Dockerfile").write_text(dockerfile)
        logger.info("Generated Dockerfile for server '%s'", server_id)

    def build(self, server_id: str, registry) -> None:
        """Build a Docker image for a registered server."""
        if not self._docker_available:
            raise RuntimeError("Docker is not available on this system")

        server = registry.get_server(server_id)
        if server is None:
            raise KeyError(f"Server '{server_id}' not found in registry")

        image_name = f"mcp-{server.id}"
        subprocess.run(
            ["docker", "build", "-t", image_name, server.source_path],
            check=True,
        )
        logger.info("Built Docker image '%s' for server '%s'", image_name, server_id)

    def run(self, server_id: str, registry) -> None:
        """Run a server as a Docker container."""
        if not self._docker_available:
            raise RuntimeError("Docker is not available on this system")

        server = registry.get_server(server_id)
        if server is None:
            raise KeyError(f"Server '{server_id}' not found in registry")

        image_name = f"mcp-{server.id}"
        container_name = f"mcp-{server.id}"
        subprocess.run(
            [
                "docker", "run", "-d",
                "--name", container_name,
                "-p", f"{server.port}:{server.port}",
                "--restart", "unless-stopped",
                image_name,
            ],
            check=True,
        )
        logger.info(
            "Started Docker container '%s' for server '%s' on port %d",
            container_name, server_id, server.port,
        )

    def stop(self, server_id: str) -> None:
        """Stop and remove a server's Docker container."""
        if not self._docker_available:
            raise RuntimeError("Docker is not available on this system")

        container_name = f"mcp-{server_id}"
        try:
            subprocess.run(["docker", "stop", container_name], check=True)
            subprocess.run(["docker", "rm", container_name], check=True)
            logger.info("Stopped and removed Docker container '%s'", container_name)
        except subprocess.CalledProcessError as exc:
            logger.error("Failed to stop container '%s': %s", container_name, exc)
            raise

    # ----------------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------------

    @staticmethod
    def _check_docker() -> bool:
        try:
            subprocess.run(
                ["docker", "info"],
                capture_output=True,
                check=True,
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            logger.info("Docker not available — container deployment disabled")
            return False
