"""
NginxConfigManager — generates, validates, and reloads nginx upstream configs.

Each registered MCP server gets an upstream block so nginx can reverse-proxy
traffic to its assigned port. SSE support requires disabled buffering.
"""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path

from src.paas.registry import ServerRegistry

logger = logging.getLogger(__name__)

UPSTREAM_TEMPLATE = """\
# Auto-generated by MCP PAAS — do not edit manually
# Server: {server_name} ({server_id})

upstream {upstream_name} {{
    server 127.0.0.1:{port};
    keepalive 16;
}}

server {{
    listen 80;
    server_name {server_name}.mcp.local;

    location / {{
        proxy_pass http://{upstream_name};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # SSE support — disable buffering
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        chunked_transfer_encoding on;
    }}
}}
"""


class NginxConfigManager:
    """Manages nginx configuration files for MCP server routing."""

    def __init__(
        self,
        registry: ServerRegistry,
        config_dir: str | Path = "/etc/nginx/conf.d",
        template_path: str | Path | None = None,
    ) -> None:
        self._registry = registry
        self._config_dir = Path(config_dir)
        self._template_path = Path(template_path) if template_path else None

    # ----------------------------------------------------------------
    # Public API
    # ----------------------------------------------------------------

    def generate_config(self, server_id: str) -> None:
        """Generate an nginx upstream config for a registered server."""
        server = self._registry.get_server(server_id)
        if server is None:
            raise KeyError(f"Server '{server_id}' not found in registry")

        config_content = UPSTREAM_TEMPLATE.format(
            server_name=server.name.lower().replace(" ", "-"),
            server_id=server.id,
            upstream_name=f"mcp_{server.id.replace('-', '_')}",
            port=server.port,
        )

        config_path = self._config_dir / f"mcp-{server.id}.conf"
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(config_content)
        logger.info("Generated nginx config for server '%s' at %s", server_id, config_path)

    def reload(self) -> None:
        """Reload nginx to pick up config changes."""
        try:
            subprocess.run(
                ["nginx", "-t"],
                capture_output=True,
                check=True,
                text=True,
            )
            subprocess.run(
                ["nginx", "-s", "reload"],
                capture_output=True,
                check=True,
            )
            logger.info("Nginx reloaded successfully")
        except subprocess.CalledProcessError as exc:
            logger.error("Nginx reload failed: %s", exc.stderr)
            raise RuntimeError(f"nginx reload failed: {exc.stderr}") from exc
        except FileNotFoundError:
            raise RuntimeError("nginx not found — is it installed?")

    def remove_config(self, server_id: str) -> None:
        """Remove the nginx config for a server."""
        config_path = self._config_dir / f"mcp-{server_id}.conf"
        if config_path.exists():
            config_path.unlink()
            logger.info("Removed nginx config for server '%s'", server_id)
        else:
            logger.warning("No nginx config found for server '%s'", server_id)

    def validate_config(self, server_id: str) -> bool:
        """Check whether a server's config file exists and is valid."""
        config_path = self._config_dir / f"mcp-{server_id}.conf"
        if not config_path.exists():
            return False
        try:
            subprocess.run(
                ["nginx", "-t"],
                capture_output=True,
                check=True,
                text=True,
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
